spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_development
    username: shop_development
    password: Hour1819
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

